# Generated by Django 4.0.3 on 2022-03-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frexco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('nascimento', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Funcionarios',
        ),
    ]
