# Generated by Django 4.0.3 on 2022-03-25 22:32

from django.db import migrations, models
import frexco.models


class Migration(migrations.Migration):

    dependencies = [
        ('frexco', '0003_funcionario_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='senha',
            field=models.CharField(blank=frexco.models.GerarSenha, default=frexco.models.GerarSenha, max_length=30, null=True),
        ),
    ]
